#端口配置
server:
  port: 7072
  servlet:
    context-path: /project
#日志级别
logging:
  level:
    root: info
    com.xcc.pjtwo: debug
#数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      enable: true
      jdbc-url: jdbc:mysql://localhost:3306/mptest?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      username: root
      password: 123456
      initialSize: 5
      minIdle: 5
      maxActive: 50
    slave:
      enable: true
      jdbc-url: jdbc:mysql://localhost:3308/mptest?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      username: root
      password: 123
      initialSize: 5
      minIdle: 5
      maxActive: 50
mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.xcc.pjtwo.sys.mapper